#+TITLE: Quantum Field Theory

* Introduction
$\gamma$ and $e^-$ behave similarly.  Light are ripples in an
electromagnetic field.  $\gamma$ should arise from quantisation of EM
field.  Should we have an $e^-$ field? /Yes/. QFT is a quantisation of
a classical field.  In QM, we promote degrees of freedom to
operators. Basic dof of QM are op-valued functions of
space-time. $\exists$ an $\infty$ number of dof; at least one for each
space-time point. QFT describes creation and annihilation of
particles. Interactions are governed by several basic principles:
- locality
- symmetry
- renormalisation group flow (decoupling of low and high energy
  processes)

** Why QFT?
- All particles of same type are indistinguishable
- QM and special relativity \Rightarrow # of particles is not
  conserved

Particles trapped in a box of size $L$. Heisenberg $\Rightarrow \Delta
p \geq \bar{h}/L$. Choose $m \ll E, \Delta E = \Delta p c$ so $\Delta
E \geq \bar{h}c/L$. When $\DeltaE \geq 2mc^2$ we can pop a particle
anti-aprticle pair out of the vacuum. Thus, when $L \leq \bar{h}/2mc$,
we can't definitely say $\exists$ only 1 paricle.

$\lambda = \bar{h}/mc$ is the Compton wavelength --- the minimum
distance at which it makes sense to localise a particle. Also the
scale at which quantum effects kick in.

Can try to write a relativistic version of the Schroedinger equation
for a single particle but something goes wrong --- either unbounded
from below energy or causality violation. These are fixed in QFT by
introduction of particle creation and annihilation.

** What is QFT good for?
- Condensed matter :: (often non-relativistic) describe simple phenomena
  such as phonons, superconductivity, fractional quantum Hall effect
- High energy physics :: Standard Model (SM) = EM + QCD + weak, (Grand
     Unified Theories etc.\ use QFT)
- Cosmology :: density perturbations
- Quantum gravity :: string theory is primarily a QFT
- Pure mathematics :: applications in topology and geometry

** History
- 1930s :: basics (Jordan, Pauli, Heisenberg, Dirac, Weisskopf) but
           $\infty$ scared them
- 1940s :: renormalisation and QED (Tomonaga, Schuringer, Feynman,
           Dyson) was a sloppy process; why $\infty - \infty =
           \text{finite}$?
- 1960s :: QFT fell out of favour as new particles (mesons and
           baryons) were discovered
- 1970s :: golden age: renormalisation group (Kodanoff, Wilson),
           $\infty$ became understood; asymptotic freedom, SM,
           connection with geometry

** Units and scales
3 fundamental dimensionful constants: $c$, $\bar{h}$ and $G$. $[c] =
LT^{-1}$, $[\bar{h}] = L^2MT^{-1}$, $[G] = L^3M^{-1}T^{-2}$. Set $c =
\bar{h} = 1$, can express everything in terms of a mass or an energy
($E = m$). Work in $\si{\electronvolt}$. To convert back to SI units
must insert relevant powers of $c$ and $\bar{h}$, e.g.\ $\lambda =
\bar{h}/mc$. $m_e = \SI{1e6}{\electronvolt}$, $\lambda_e =
\SI{2e-12}{\meter}$.

If $x$ has mass dimension $d$, wirte $[x] = d$, e.g.\ $[G] = -2$,
$G=\bar{h}c/M_p^2 \to 1/M_p^2$ where $M_p \sim
\SI{1e19}{\giga\electronvolt}$ is the Planck scale.
